### ISSUE TITLE
老哥要是有空写个详细的结构说明就好了

### ISSUE THREAD

**Issue by l0n9er** [meikoz/EasyApp#13]
刚接触Android不久。

**Comment by racofix** [comment]
@l0n9er  老哥最近在写一个更流弊的架构, 到时候会出详细的文档.  欢迎互相学习

**Comment by l0n9er** [comment]
@meikoz 更牛逼的我怕是更加看不懂，你这个封装的好好，我看得挺吃力ing，努力学习。新手上路中。

**Comment by racofix** [comment]
@l0n9er https://github.com/meikoz/architecture 这个简洁版. 后面我会完善这个..

**Comment by l0n9er** [comment]
@meikoz 关注了，老哥加油，我继续啃你这项目。

**Comment by l0n9er** [comment]
@meikoz 老哥方便留个qq，或者别的联系方式么
