### ISSUE TITLE
谢谢，提个疑问，关于BaseActivity

### ISSUE THREAD

**Issue by RXlung** [meikoz/EasyApp#15]
BaseActivity中的getLogiClazz()返回的空，这样的话初始化 一直进不去啊；；这样导致onDestroy报空指针
是我哪写的不对吗？？   一下使我的代码：
public abstract class BaseActivity extends FragmentActivity implements BaseView {
	private String TAG = "BaseActivity";
	protected BasePresenter mPresenter;

	protected abstract int getLayoutResource(); // 返回布局id

	protected abstract void onInitialization(Bundle bundle); // 初始化数据

	protected Class getLogiClazz() {
		return null;
	}

	protected void onInitDataMvp() {
		if (getLogiClazz() != null) {  //为空不进去？
			MyLog.i(TAG, "onInitDataMvp方法");
			mPresenter = getLogicImpl();// 拿到实例 presenter绑定了view
		}
	}

	@Override
	protected void onCreate(Bundle arg0) {
		super.onCreate(arg0);
		requestWindowFeature(Window.FEATURE_NO_TITLE);// 全屏
		if (getLayoutResource() != 0) {
			setContentView(getLayoutResource());
		}
		ButterKnife.bind(this);
		this.onInitialization(arg0);
		MyLog.i(TAG, "onCreate方法");
		this.onInitDataMvp();/// 这个是关于mvp的初始化操作
	}

	@Override
	protected void onStart() {
		super.onStart();
		if (mPresenter != null && !mPresenter.isViewBind()) { // 控制器不为空 没绑定view
			MyLog.i(TAG,"onStart()方法初始化");
			LogicProxy.getInstance().bind(getLogiClazz(), this); // 去绑定
		}
	}

	/**
	 * 关于mvp的初始化类等封装
	 * 
	 * @return
	 */
	public <T> T getLogicImpl() {
		MyLog.i(TAG, "getLogicImpl方法");
		return (T) LogicProxy.getInstance().bind(getLogiClazz(), this); // bind(class类，view)绑定
	}

	@Override
	protected void onDestroy() {
		super.onDestroy();
		ButterKnife.unbind(this);
		//先暂时去掉了这 有疑问因为报空指针，上面的getLogiClazz一直是空的啊
//		LogicProxy.getInstance().unbind(getLogiClazz(), this); // 解除绑定
//		if (mPresenter != null)
//			mPresenter.detachView();
	}
}

**Comment by racofix** [comment]
class MainActivity extends Activity implements MainLogicI.MainView {

   @Override
    protected Class getLogicClazz() {
        return your interface MainLogicI class;// MainLogic是Presenter要实现的接口
    }

    @Override
    protected void onInitData2Remote() {
        super.onInitData2Remote();
       ((MainLogicImpl) mPresenter).onLoadData2Remote();
    }

    @Override
    public void onLoadSuccessHandler(String response) {
    //response是Presenter中返回的数据
   }
}
