### ISSUE TITLE
感谢大神贡献的项目

### ISSUE THREAD

**Issue by ThreadDeath** [meikoz/EasyApp#6]
一段时间没看这个项目了，感觉又优化更新很多，但是之前的demo怎么没了，文档好像也没之前详细啊

**Comment by racofix** [comment]
感谢您的关注与支持，之前的demo在master-backups分支上，文档现在wiki上有一部分后续会慢慢完善

**Comment by kuaige** [comment]
可以来个群讨论下不?

**Comment by ThreadDeath** [comment]
这个可以有

**Comment by live17909** [comment]
感觉还是不少问题呀。。。。群号有吗？
