### ISSUE TITLE
怎么办？更新了下as好象就这样了，怎么也修不成功？求助  as2.2.3

### ISSUE THREAD

**Issue by live17909** [meikoz/EasyApp#7]
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find com.meikoz.basic.core:1.0.6:.
     Required by:
         Basic-master:app:unspecified
   > Could not find com.android.support:appcompat-v7:23.4.0.
     Required by:
         Basic-master:app:unspecified > com.meikoz.tabstrip:tabstrip:1.0.0

**Comment by live17909** [comment]
总是这个错。。。

**Comment by racofix** [comment]
gradle clean
